# Generated by Django 4.0.6 on 2022-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_author_image_content_image_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.TextField(default='hello'),
        ),
    ]
